"""add_is_dashboard_pro_to_users

Revision ID: 08a317e23cc3
Revises: c1698e15c7ad
Create Date: 2025-12-07 16:47:55.752178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a317e23cc3'
down_revision: Union[str, None] = 'c1698e15c7ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_dashboard_pro', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_dashboard_pro')
    # ### end Alembic commands ###
