"""Add name and email to event_participants

Revision ID: 0e5b19c6be28
Revises: 2c172d7e4f9f
Create Date: 2025-12-28 21:00:27.646963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5b19c6be28'
down_revision: Union[str, None] = '2c172d7e4f9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_participants', sa.Column('name', sa.String(), nullable=True))
    op.add_column('event_participants', sa.Column('email', sa.String(), nullable=True))
    op.alter_column('event_participants', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_participants', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('event_participants', 'email')
    op.drop_column('event_participants', 'name')
    # ### end Alembic commands ###
