"""add deleted_at to events

Revision ID: 18b2481347f8
Revises: 2cdcb50e38d7
Create Date: 2025-12-04 13:31:02.993930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b2481347f8'
down_revision: Union[str, None] = '2cdcb50e38d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reviews', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'deleted_at')
    op.drop_column('events', 'deleted_at')
    # ### end Alembic commands ###
