"""add_chat_models

Revision ID: 2136482fa6d8
Revises: e6b1238d2f65
Create Date: 2025-12-10 20:33:41.807404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2136482fa6d8'
down_revision: Union[str, None] = 'e6b1238d2f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('event_embeddings_embedding_idx', table_name='event_embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_table('event_embeddings')
    op.drop_index('expert_embeddings_embedding_idx', table_name='expert_embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_table('expert_embeddings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expert_embeddings',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('source_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='expert_embeddings_pkey')
    )
    op.create_index('expert_embeddings_embedding_idx', 'expert_embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_table('event_embeddings',
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('source_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('event_id', name='event_embeddings_pkey')
    )
    op.create_index('event_embeddings_embedding_idx', 'event_embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
