"""add_deleted_at_to_organizations

Revision ID: 2c172d7e4f9f
Revises: d3d41298509b
Create Date: 2025-12-28 17:27:33.322948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c172d7e4f9f'
down_revision: Union[str, None] = 'd3d41298509b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('org_id', sa.UUID(), nullable=True))
    op.alter_column('follows', 'followee_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'follows', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.add_column('organizations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('reviews', 'reviewee_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'reviewee_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('organizations', 'deleted_at')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.alter_column('follows', 'followee_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('follows', 'org_id')
    # ### end Alembic commands ###
