"""Add organization_id to events

Revision ID: 489498044e07
Revises: 6a9f3061ffe5
Create Date: 2025-12-31 13:10:03.254323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '489498044e07'
down_revision: Union[str, None] = '6a9f3061ffe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'events', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'organization_id')
    # ### end Alembic commands ###
