"""Add meeting_url and sync

Revision ID: 5f0bf587331b
Revises: 0e5b19c6be28
Create Date: 2025-12-30 19:18:37.342474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f0bf587331b'
down_revision: Union[str, None] = '0e5b19c6be28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_checklist_items', 'link_url')
    op.drop_column('event_checklist_items', 'audience_role')
    op.drop_column('event_checklist_items', 'visibility')
    op.add_column('events', sa.Column('meeting_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'meeting_url')
    op.add_column('event_checklist_items', sa.Column('visibility', postgresql.ENUM('internal', 'external', name='checklistvisibility'), autoincrement=False, nullable=False))
    op.add_column('event_checklist_items', sa.Column('audience_role', postgresql.ENUM('organizer', 'committee', 'speaker', 'sponsor', 'audience', 'student', 'teacher', name='eventparticipantrole'), autoincrement=False, nullable=True))
    op.add_column('event_checklist_items', sa.Column('link_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
