"""Add cascading deletes to user foreign keys

Revision ID: 6b434b9b4e23
Revises: 4f67c4b02790
Create Date: 2025-10-30 15:41:22.144515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b434b9b4e23'
down_revision: Union[str, None] = '4f67c4b02790'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('educations_user_id_fkey', 'educations', type_='foreignkey')
    op.create_foreign_key(None, 'educations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('job_experiences_user_id_fkey', 'job_experiences', type_='foreignkey')
    op.create_foreign_key(None, 'job_experiences', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('profiles_user_id_fkey', 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key('profiles_user_id_fkey', 'profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'job_experiences', type_='foreignkey')
    op.create_foreign_key('job_experiences_user_id_fkey', 'job_experiences', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'educations', type_='foreignkey')
    op.create_foreign_key('educations_user_id_fkey', 'educations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
