"""add_promo_fields_to_event_participants

Revision ID: 6ee0337837d4
Revises: 868840fc0a73
Create Date: 2026-01-01 13:03:41.272595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee0337837d4'
down_revision: Union[str, None] = '868840fc0a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_participants', sa.Column('promo_link', sa.String(), nullable=True))
    op.add_column('event_participants', sa.Column('promo_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_participants', 'promo_image_url')
    op.drop_column('event_participants', 'promo_link')
    # ### end Alembic commands ###
