"""create_communication_logs_table

Revision ID: 7fe70ea36a18
Revises: d85c7402a06d
Create Date: 2025-12-09 15:32:36.707603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fe70ea36a18'
down_revision: Union[str, None] = 'd85c7402a06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('EMAIL', 'NOTIFICATION', name='communicationtype'), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='communicationstatus'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_logs_recipient'), 'communication_logs', ['recipient'], unique=False)
    op.create_index(op.f('ix_communication_logs_status'), 'communication_logs', ['status'], unique=False)
    op.drop_index('expert_embeddings_embedding_idx', table_name='expert_embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_table('expert_embeddings')
    op.drop_index('event_embeddings_embedding_idx', table_name='event_embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_table('event_embeddings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_embeddings',
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.TEXT(), server_default=sa.text("'text-embedding-3-small'::text"), autoincrement=False, nullable=True),
    sa.Column('embedding_version', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('event_id', name='event_embeddings_pkey')
    )
    op.create_index('event_embeddings_embedding_idx', 'event_embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_table('expert_embeddings',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.TEXT(), server_default=sa.text("'text-embedding-3-small'::text"), autoincrement=False, nullable=True),
    sa.Column('embedding_version', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='expert_embeddings_pkey')
    )
    op.create_index('expert_embeddings_embedding_idx', 'expert_embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_communication_logs_status'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_recipient'), table_name='communication_logs')
    op.drop_table('communication_logs')
    # ### end Alembic commands ###
