"""Add is_attendance_enabled to events

Revision ID: 868840fc0a73
Revises: 489498044e07
Create Date: 2025-12-31 13:46:28.552170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '868840fc0a73'
down_revision: Union[str, None] = '489498044e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_attendance_enabled', sa.Boolean(), server_default='true', nullable=False))
    # Remove the server default if you don't want it to persist for new rows (though for boolean flags it's usually fine)
    # op.alter_column('events', 'is_attendance_enabled', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'is_attendance_enabled')
    # ### end Alembic commands ###
