"""add_fintech_fields

Revision ID: d3d41298509b
Revises: f1e2d3c4b5a6
Create Date: 2025-12-23 23:13:00.910245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3d41298509b'
down_revision: Union[str, None] = 'f1e2d3c4b5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_transactions')
    # op.drop_index('event_embeddings_embedding_idx', table_name='event_embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    
    # Create enum type safely
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'eventpaymentstatus') THEN CREATE TYPE eventpaymentstatus AS ENUM ('pending', 'verified', 'rejected'); END IF; END $$;")

    op.alter_column('event_participants', 'payment_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('pending', 'verified', 'rejected', name='eventpaymentstatus'),
               existing_nullable=True,
               postgresql_using="payment_status::eventpaymentstatus")
    op.add_column('events', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('currency', sa.String(), nullable=True))
    # op.drop_index('expert_embeddings_embedding_idx', table_name='expert_embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.add_column('organizations', sa.Column('bank_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'bank_details')
    # op.create_index('expert_embeddings_embedding_idx', 'expert_embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_column('events', 'currency')
    op.drop_column('events', 'price')
    op.alter_column('event_participants', 'payment_status',
               existing_type=sa.Enum('pending', 'verified', 'rejected', name='eventpaymentstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using="payment_status::varchar")
    op.execute("DROP TYPE IF EXISTS eventpaymentstatus")
    # op.create_index('event_embeddings_embedding_idx', 'event_embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_table('event_transactions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'completed', 'failed', 'refunded', name='eventtransactionstatus'), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('proof_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stripe_intent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='event_transactions_event_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='event_transactions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='event_transactions_pkey')
    )
    # ### end Alembic commands ###
