"""Sync user schema

Revision ID: d85c7402a06d
Revises: 
Create Date: 2025-12-09 13:08:55.781410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd85c7402a06d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('title', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('average_rating', sa.Float(), server_default=sa.text('0.0'), nullable=False))
    op.add_column('profiles', sa.Column('availability', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_dashboard_pro', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_dashboard_pro')
    op.drop_column('profiles', 'availability')
    op.drop_column('profiles', 'average_rating')
    op.drop_column('profiles', 'title')
    # ### end Alembic commands ###
