"""add_cascade_to_profile_tags

Revision ID: e6b1238d2f65
Revises: 575ecbe8adb2
Create Date: 2025-12-10 00:54:53.171869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_cascade_to_profile_tags

Revision ID: e6b1238d2f65
Revises: 575ecbe8adb2
Create Date: 2025-12-10 00:54:53.171869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6b1238d2f65'
down_revision: Union[str, None] = '575ecbe8adb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profile_skills_profile_id_fkey', 'profile_skills', type_='foreignkey')
    op.drop_constraint('profile_skills_skill_id_fkey', 'profile_skills', type_='foreignkey')
    op.create_foreign_key(None, 'profile_skills', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'profile_skills', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('profile_tags_tag_id_fkey', 'profile_tags', type_='foreignkey')
    op.drop_constraint('profile_tags_profile_id_fkey', 'profile_tags', type_='foreignkey')
    op.create_foreign_key(None, 'profile_tags', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'profile_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile_tags', type_='foreignkey')
    op.drop_constraint(None, 'profile_tags', type_='foreignkey')
    op.create_foreign_key('profile_tags_profile_id_fkey', 'profile_tags', 'profiles', ['profile_id'], ['id'])
    op.create_foreign_key('profile_tags_tag_id_fkey', 'profile_tags', 'tags', ['tag_id'], ['id'])
    op.drop_constraint(None, 'profile_skills', type_='foreignkey')
    op.drop_constraint(None, 'profile_skills', type_='foreignkey')
    op.create_foreign_key('profile_skills_skill_id_fkey', 'profile_skills', 'skills', ['skill_id'], ['id'])
    op.create_foreign_key('profile_skills_profile_id_fkey', 'profile_skills', 'profiles', ['profile_id'], ['id'])
    # ### end Alembic commands ###
