"""add_walk_in_token_id_to_event_participants

Revision ID: f6da033b1814
Revises: 868840fc0a73
Create Date: 2026-01-01 13:59:13.991176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6da033b1814'
down_revision: Union[str, None] = '868840fc0a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_participants', 'promo_link')
    op.drop_column('event_participants', 'promo_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_participants', sa.Column('promo_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event_participants', sa.Column('promo_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
