"""add school to education

Revision ID: fd8b270e962b
Revises: e28529df69ac
Create Date: 2026-01-02 14:30:20.483669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8b270e962b'
down_revision: Union[str, None] = 'e28529df69ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('educations', sa.Column('school', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('educations', 'school')
    # ### end Alembic commands ###
