export const APU_DEGREES = [
    "Banking and Finance (Investment Analytics)",
    "Banking and Finance (FinTech)",
    "Actuarial Studies",
    "Actuarial Studies (Data Analytics)",
    "Actuarial Studies (FinTech)",
    "Financial Technology (FinTech)",
    "Computer Games Development",
    "Accounting and Finance",
    "Accounting and Finance (Forensic Accounting)",
    "Accounting and Finance (Forex and Investments)",
    "Accounting and Finance (Accounting Technology)",
    "Banking and Finance",
    "CS (Digital Forensics)",
    "CS (Cyber Security)",
    "Software Engineering",
    "CS (AI)",
    "Interactive Media (VR/AR)",
    "IT (FinTech)",
    "IT (Business Information Systems)",
    "IT (Sustainable Computing)",
    "Computer Science",
    "CS (Data Analytics)",
    "Information Technology",
    "IT (Information System Security)",
    "IT (Cloud Engineering)",
    "IT (IoT)",
    "IT (Digital Transformation)",
];

export const COUNTRIES = [
    "Malaysia",
    "Singapore",
    "Indonesia",
    "Thailand",
    "Vietnam",
    "Philippines",
    "China",
    "India",
    "Japan",
    "South Korea",
    "Taiwan",
    "Hong Kong",
    "Australia",
    "New Zealand",
    "United Kingdom",
    "United States",
    "Canada",
    "Germany",
    "France",
    "Italy",
    "Spain",
    "Netherlands",
    "Switzerland",
    "Sweden",
    "Norway",
    "Denmark",
    "Finland",
    "Russia",
    "Ukraine",
    "Poland",
    "Brazil",
    "Argentina",
    "Mexico",
    "South Africa",
    "Egypt",
    "United Arab Emirates",
    "Saudi Arabia",
    "Qatar",
    "Turkey",
    "Iran",
    "Pakistan",
    "Bangladesh",
    "Sri Lanka",
    "Nepal",
    "Myanmar",
    "Cambodia",
    "Laos",
    "Brunei",
    "Other"
].sort();
